DATA_DIR: "/home/billbrod/Desktop/synth_example/"
TEXTURE_DIR: "/home/billbrod/Desktop/textures/cropped512-gray-jpg"

REF_IMAGE_TEMPLATE_PATH: "{DATA_DIR}/ref_images/{image_name}.png"
METAMER_TEMPLATE_PATH: "{DATA_DIR}/metamers/{model_name}/{image_name}/opt-{optimizer}_loss-{loss}_penalty-{range_lambda}/stop-iters-{stop_iters}_ctf-{coarse_to_fine}_ctf-crit-{ctf_criterion}_ctf-iters-{ctf_iters}/seed-{seed}_init-{init_type}_lr-{learning_rate}_e0-{min_ecc:.03f}_em-{max_ecc:.03f}_iter-{max_iter}_stop-crit-{stop_criterion}_gpu-{gpu}_metamer.png"
MAD_TEMPLATE_PATH: "{DATA_DIR}/mad_images/1-{model_name_1}_2-{model_name_2}/{image_name}/fix-{fix_model_num}_synth-{synth_model_num}_{synth_target}/opt-{optimizer}_tradeoff-{tradeoff_lambda}_penalty-{range_lambda}_stop-iters-{stop_iters}/seed-{seed}_init-{init_type}_lr-{learning_rate}_e0-{min_ecc:.03f}_em-{max_ecc:.03f}_iter-{max_iter}_stop-crit-{stop_criterion}_gpu-{gpu}_mad.png"

# path to the foveated-metamers repo, which we use for our foveated ventral
# stream models: https://github.com/billbrod/foveated-metamers/
FOVEATED_METAMERS_PATH: '/home/billbrod/Documents/foveated-metamers'
